#!/bin/bash

do_overclock_rg35xx() {
    echo "$1" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
}


if test "${1}" = "start"
then
    OVALUE=$(grep -E '^[ ]*overclocking[ ]*=[ ]*.*[ ]*$' /boot/batocera-boot.conf | sed -e s+"^[ ]*overclocking[ ]*=[ ]*\(.*\)[ ]*$"+"\1"+)

    # ULTRALOW      LOW           MEDIUM          HIGH            TURBO   EXTREME
    # 240000 504000 720000 840000 1008000 1104000 1200000 1296000 1392000 1488000
	    case "${OVALUE}" in
		"extreme")
		    do_overclock_rg35xx 1488000
		    ;;
		"turbo")
		    do_overclock_rg35xx 1392000
		    ;;
		"high")
		    do_overclock_rg35xx 1200000
		    ;;
		"none")
		    do_overclock_rg35xx 1008000
		    ;;
		"low")
		    do_overclock_rg35xx 720000
		    ;;
		"powersave")
		    do_overclock_rg35xx 240000
		    ;;
		*)
		    # default
		    do_overclock_rg35xx 1008000
		    ;;
	    esac
fi

