#!/bin/bash

# Path to lid sensor
HALLKEY="/sys/class/power_supply/axp2202-battery/hallkey"

case "$1" in
    thaw|resume)
        if [ -f "$HALLKEY" ] && [ "$(cat "$HALLKEY")" = "0" ]; then
            ( sleep 2 && pm-suspend ) &
        fi
        ;;
esac

exit 0
