#!/bin/bash

case "$1" in
    start)
            batocera-settings-set system.lid shutdown
        ;;
    stop)
            batocera-settings-set system.lid suspend
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac
 
exit $?
