#!/bin/bash

do_overclock() {
    echo "$1" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
    echo "$1" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
}


if test "${1}" = "start"
then
    OVALUE=$(grep -E '^[ ]*overclocking[ ]*=[ ]*.*[ ]*$' /boot/batocera-boot.conf | sed -e s+"^[ ]*overclocking[ ]*=[ ]*\(.*\)[ ]*$"+"\1"+)

    # ULTRALOW      LOW             MEDIUM  HIGH    TURBO   EXTREME
    # 480000 720000 1032000 1104000 1200000 1296000 1416000 1512000 

	    case "${OVALUE}" in
		"none")
		    do_overclock 1512000
		    ;;
		"turbo")
		    do_overclock 1416000
		    ;;
		"high")
		    do_overclock 1296000
		    ;;
		"medium")
		    do_overclock 1200000
		    ;;
		"low")
		    do_overclock 720000
		    ;;
		"powersave")
		    do_overclock 480000
		    ;;
		*)
		    # default
		    do_overclock 1512000
		    ;;
	    esac
fi

