################################################################################
#
# LIBRETRO-FLYCAST_XTREME
#
################################################################################
# version.: Commits on Dec 8, 2021
LIBRETRO_FLYCAST_XTREME_VERSION = fd9196b40b2198dfa3bed3a16dda60822f24ee66
LIBRETRO_FLYCAST_XTREME_SITE = $(call github,KMFDManic,flycast,$(LIBRETRO_FLYCAST_XTREME_VERSION))
LIBRETRO_FLYCAST_XTREME_LICENSE = GPLv2

LIBRETRO_FLYCAST_XTREME_PLATFORM = $(LIBRETRO_PLATFORM)
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS = HAVE_OPENMP=1

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = rpi4_64
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2712),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = rpi5_64
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2837),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = rpi3_64
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2836),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = rpi2
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3326),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = RK3326
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_H700)$(BR2_PACKAGE_BATOCERA_TARGET_A133),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = odroid-n2
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_H3),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = sun8i
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm LDFLAGS=-lrt

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_H5)$(BR2_PACKAGE_BATOCERA_TARGET_H6),y)
LIBRETRO_FLYCAST_XTREME_PLATFORM = arm64
LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64 LDFLAGS=-lrt
endif

define LIBRETRO_FLYCAST_XTREME_BUILD_CMDS
    $(TARGET_CONFIGURE_OPTS) $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile \
		platform="$(LIBRETRO_FLYCAST_XTREME_PLATFORM)" $(LIBRETRO_FLYCAST_XTREME_EXTRA_ARGS) \
        GIT_VERSION="-$(shell echo $(LIBRETRO_FLYCAST_XTREME_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_FLYCAST_XTREME_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/km_flycast_xtreme_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/flycast-xtreme_libretro.so

    cp "$(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/retroarch/libretro/libretro-flycast-xtreme/flycast-xtreme_libretro.info" \
        "$(TARGET_DIR)/usr/share/libretro/info/"
endef

$(eval $(generic-package))
