#!/bin/sh

#initialize the counter for the bar
counter=$(($(ls /etc/init.d/S*|wc -l)-1))
multiplier=$(echo "100/$counter"|bc -l)


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
            num=$(echo "$multiplier * $counter" |bc -l)
            counter=$(($counter-1))
            /usr/bin/progressbar $num
	    $i stop
	    ;;
    esac
done
/usr/bin/progressbar 0
