#!/bin/sh

# Initialize the counter for the bar
counter=4
multiplier=$(echo "100/$(($(ls /etc/init.d/S[0-2]*|wc -l)-1))"|bc -l)

# We need the graphics module in order to use SDL since we are
# using the sdl-compat/SDL2 for rendering
insmod /lib/modules/mali_kbase.ko

# Call the charger process
/usr/bin/charger

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    script_number=$(echo "$i" | sed -n 's/.*\/S\([0-9]\+\).*/\1/p')
	    if [ "$script_number" -le 31 ]; then
                num=$(echo "$multiplier * $counter" |bc -l)
                counter=$(($counter + 1))
                /usr/bin/progressbar $num
	    fi
	    ;;
    esac

    echo $(date +"%F %T,%3N")": ${i} - started" >> /var/run/boot.log
done
